### ISSUE TITLE
❎ Directory links couldn't be fetched

### ISSUE THREAD

**Issue by Joeissa** [ibnsamy96/linkbox-downloader#15]
hello, 

I am trying to run the downloader but I am getting this error every time. 

  ❎ Directory links couldn't be fetched
—  Couldn't complete the fetch process, make sure that you're connected and LinkBox is available.

any ideas what might be causing this?

**Comment by ibnsamy96** [comment]
Can use access linkbox normally from your browser?

If yes, please run the utility in dev mode using `lbx-downloader -d`, this mode will add more info related to errors. Copy the new info it will print and share it in a comment.

If you can't open linkbox in your browser, It seems that it's blocked in your region or that linkbox has blocked your IP address due to strange behavior it detected.
Anyway, It's always better to use working proxies or simply you can use a VPN. Please try one of those solutions and share the results in a comment. And make sure that the proxy is working, the internet is full of dead proxies!

**Comment by Joeissa** [comment]
Can use access Linkbox normally from your browser? **Yes, I can without any problems. I also can download it manually** 

If yes, please run the utility in dev mode using lbx-downloader -d, this mode will add more info related to errors. Copy the new info it will print and share it in a comment. **I did, the error was the same** 

I tried with and without VPN, Manually I can download .
I will keep troubleshooting and will update if I find anything.

**Comment by Joeissa** [comment]
```
file:///C:/Users/PC_USER/AppData/Roaming/npm/node_modules/@ibnsamy96/linkbox-downloader/prod/helpers.js:1
import{isCancel,cancel,note,spinner}from"@clack/prompts";import*as fs from"fs";import path from"path";import paths from"./paths.js";import{HttpsProxyAgent}from"https-proxy-agent";const addCancelPrompt=(t,e)=>{isCancel(t)&&(cancel(e),process.exit(0))},addNote=(t,e)=>{note(e,t)},addTimer=(t,e,r)=>{var s=spinner();return r.push({sp:s,errorMessage:e}),s.start(t),s},createDirIfNotExist=t=>{fs.existsSync(t)||fs.mkdirSync(t)},createFileIfNotExist=t=>{fs.existsSync(t)||fs.writeFile(t,"","utf8",()=>{})},generateFilePath=t=>(t=t.map(t=>t.trim()),path.join(...t)),isFileExist=t=>!!fs.existsSync(t);function parseConfigsFile(t){var e={};for(const i of fs.readFileSync(t?.filePath||paths.configs,"utf8").split("\n")){var[r,s]=i.split("=");e[r]=s}return e}function stringifyConfigsFile(t){var e=[];for(const s in t){var r=s+"="+t[s];e.push(r)}return e.join("\n")}const generateProxyUrl=t=>{var{protocol:t,host:e,port:r,username:s,password:i}=t;return s&&i?t+`://${s}:${i}@${e}:`+r:t+`://${e}:`+r},createProxyAgent=t=>new HttpsProxyAgent(t);export{addCancelPrompt,addNote,addTimer,createDirIfNotExist,createFileIfNotExist,generateFilePath,isFileExist,parseConfigsFile,stringifyConfigsFile,generateProxyUrl,createProxyAgent};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^

TypeError: Cannot destructure property 'protocol' of 't' as it is undefined.
    at generateProxyUrl (file:///C:/Users/PC_USER/AppData/Roaming/npm/node_modules/@ibnsamy96/linkbox-downloader/prod/helpers.js:1:896)
    at createProxiesAgents (file:///C:/Users/PC_USER/AppData/Roaming/npm/node_modules/@ibnsamy96/linkbox-downloader/prod/downloader.js:1:652)
    at createProxiesAgents.next (<anonymous>)
    at getData (file:///C:/Users/PC_USER/AppData/Roaming/npm/node_modules/@ibnsamy96/linkbox-downloader/prod/downloader.js:1:860)
    at getBaseFolderName (file:///C:/Users/PC_USER/AppData/Roaming/npm/node_modules/@ibnsamy96/linkbox-downloader/prod/downloader.js:1:3551)
    at main (file:///C:/Users/PC_USER/AppData/Roaming/npm/node_modules/@ibnsamy96/linkbox-downloader/prod/index.js:2:1106)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cancelationMessage: "Couldn't complete the fetch process, make sure that you're connected and LinkBox is available."
}

Node.js v18.18.0


```

The Error from the -d run

**Comment by SteveLosive** [comment]
> hello,
> 
> I am trying to run the downloader but I am getting this error every time.
> 
> ❎ Directory links couldn't be fetched — Couldn't complete the fetch process, make sure that you're connected and LinkBox is available.
> 
> any ideas what might be causing this?

same issue here

also this is the detailed error I got

TypeError: Cannot destructure property 'proxyAgent' of 'roundedProxiesCreator.next(...).value' as it is undefined.
    at getData (file:///C:/Users/User/AppData/Roaming/npm/node_modules/@ibnsamy96/linkbox-downloader/prod/downloader.js:1:822)
    at getAllDownloadLinks (file:///C:/Users/User/AppData/Roaming/npm/node_modules/@ibnsamy96/linkbox-downloader/prod/downloader.js:1:3075)
    at main (file:///C:/Users/User/AppData/Roaming/npm/node_modules/@ibnsamy96/linkbox-downloader/prod/index.js:2:1136)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cancelationMessage: "Couldn't complete the fetch process, make sure that you're connected and LinkBox is available."
}

Node.js v20.8.0

**Comment by agret** [comment]
I get the same error but I can't start it in dev mode as it just goes straight into config editing

```
lbx-downloader --dev
T  Welcome to LinkBox Downloader
|
*  What is the link to be downloaded?
|  https://www.linkbox.to/a/s/<share-token>?pid=<folder-pid>
—
T  Welcome to LinkBox Downloader Configurations
x  What do you want to update in the utility configs?
|  Change the downloads location
```

I can't type the link url as it is only has focus on the lower down config editing part rather than the input box
